//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppYTVideoAlbum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public int IdVideo { get; set; }
        public string UrlVideo { get; set; }
        public string Tittle { get; set; }
        public string UrlImg { get; set; }
        public string Descript { get; set; }
    }
}
